### ISSUE TITLE
Programming platform for your code

### ISSUE THREAD

**Issue by zhangysh1995** [huanjiayang/nccscc2530dev#1]
I'm student working on CC2530DK at Prof. Shuanghua Yang's lab and just got stuck on programming for this kit. I received forward email from him and know you had experience on this issue.
I found in Contiki documentation that several drivers for SmartRF05EB are not available yet and this operating system performance is unstable for 8051. There is another choice as using IAR Embedded Workbench to program.
As I'm just starting to get familiar with the development kit, could you give specific recommendations to choose from these two platform? Or could you tell me your own experiences when programming with CC2530 before?

Thank you,
Yushan

**Comment by momamman** [comment]
Hi Yushan,

 

I would personally recommend that you use the contiki provided kit. It depends on what you’re comfortable with really; and what project youre working on i.e what your actual project does. Mine was environmental system monitoring so basic reading, sending, math operations were needed coupled with some knowledge of C programming. 

What particular problems are you having ?

 

PS. This was 4 years ago for me…im very rusty

**Comment by zhangysh1995** [comment]
Thanks for your reply. 
I decided to talk with him more about the project details first. Then I will try to find more former usages of these tools. I might come back to you later.

Yushan

**Comment by huanjiayang** [comment]
Yo Moh, Long time no see how you doing?! ☺

Yushan,
I’d suggest you go with ConTiki for now, the IAR platform is limited to 32k for compiled target. We don’t have a license for IAR it cost too much. It depends on what you want to do with it really, what’s your project?

Regards,
Huanjia

**Comment by momamman** [comment]
Hi Huanjia,

 

Been too long. Hows you doing and how is the family ? seems like youre no longer in Loughborough Uni . Hope all is well

**Comment by zhangysh1995** [comment]
I think most of my work is to port learning materials from sensinode to TI CC2530DK and try to design new materials for this course - _wireless sensor networks_.

I started using both Contiki and IAR EW and will determine later on the materials I will go through. These platforms are good to learn and might be introduced together to the materials.

Thank you.

**Comment by huanjiayang** [comment]
Hi mate, yeh not too bad at all I work at IBM UK now as the head of their development team in UK delivery centre headquarter, decided that academia career is not for me so fancied a change  and so far so good, should have done it even earlier ;)

How are you doing what you up for atm?

**Comment by momamman** [comment]
That’s really great. Impressive too. Im happy everything is going well. 

 

Im alright really, Im working for my government here – commission responsible for the country’s Identity Database. I work in Information Security department. Its alright, nothing particularly exciting yet but im patient.
